### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kwsch** [Martmists-GH/SV-Exlaunch#1]
In this commit (https://github.com/Martmists-GH/SV-Exlaunch/commit/ac7cc7a055a855f18f28a21bcb4c65c1856dd525#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7) the license was changed from GPLv2 to BSD 3-Clause.

Is this something the original exlaunch authors & contributors gave you permission to relicense their code? The BSD 3-Clause license is not the same as GPLv2.

**Comment by Martmists-GH** [comment]
As you can see in NOTICE, I've made note of the original licenses of previous commits and the exlaunch project. Only the commits added after those are to be considered BSD-3.

Permission has also been granted by the exlaunch developer to license this project under BSD-3: 
![image](https://user-images.githubusercontent.com/16361449/202767808-12c87329-f353-41dc-84bc-486ef225d4f6.png)

IANAL and as such if the phrasing in NOTICE is not legally sound I'm happy to change it if anyone with more legal expertise is willing to make a proper write-up.
